
# Fill in the IPs from `terraform output` in infra/terraform/.
# public_ip = used by Ansible/SSH to reach the node from your laptop
# private_ip = used internally for k3s server<->agent communication

[server]
control-plane ansible_host=54.74.194.170 private_ip=172.31.1.23

[agents]
worker-0 ansible_host=52.16.184.32 private_ip=172.31.1.160
worker-1 ansible_host=18.203.246.146 private_ip=172.31.1.112

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'
